/*
PROYECTO INTEGRADOR

INTEGRANTES: 
SANTIAGO ENRIQUE HERNANDEZ CONTRERAS
DAVID NICOLAS CHILITO
SANTIAGO BAQUERO
VERSION 6
*/

/*CREACION DEL PROYECTO INTEGRADOR*/
DROP DATABASE IF EXISTS techcare; --BORRAMOS LA BASE DE DATOS SI YA EXISTE PARA QUE CADA VEZ QUE SE EJECUTE EL SCRIPT NO SE DUPLIQUEN LOS VALORES
CREATE DATABASE techcare;/*CREAMOS UNA TABLA PARA ALAMCENAR TODAS LAS DEMAS TABLAS QUE SE VAN A ALMACENAR*/
USE techcare;/*ABRIMOS NUESTRO TABLA O ENTRAMOS */

CREATE TABLE negocio(/*CREAMOS UNA TABLA DE NEGOCIO DONDE VAMOS A ALMACENAR LAS DIRECCIONE*/
    correo VARCHAR(30) NOT NULL PRIMARY KEY,/*EL CORREO DONDE PODEMOS ENVIAR INFORMACION AL CLIENTE COMO A MIEMBROS DE LA TIENDA FISICA*/
    direccion_negocio VARCHAR(20) NOT NULL,/*ES LA UBICACION DONDE ESTARA LA TIENDA FISICA PARA HACER ESTOS SOPORTES EN LA TIENDA*/
    horario_atencion  VARCHAR(20) NOT NULL,/*SERA LAS HORAS QUE PONDRA VENIR LOS CLIENTES O LLAMAR PARA HACER ESTOS SOPORTES EN LA TIENDA O EN LA CASA O EMPRESA*/
    telefono VARCHAR(13) NOT NULL /*EL NUMERO DONDE PODRAS CONTACTAR CON LA TIENDA PARA SOLICITAR EL SOPORTE EN LA TIENDA COMO EN SU CASA*/
);/*CERRAMOS EL CONTENIDO QUE TENDRA NUESTRA TABLA DE NEGOCIO*/

CREATE table empleados(/*CREAREMOS UNA TABLA PARA EL EMPLEADO DONDE TENDREMOS LA INFORMACION DE ESTE */
    id_empleado INT NOT NULL PRIMARY KEY,
    primer_nombre_empleado VARCHAR(20) NOT NULL,/*SE GUARDA EL PRIMER NOMBRE PARA MEJORAR EL RENDIMIENTO DE ALMACENAMIENTO*/
    segundo_nombre_empleado VARCHAR(20) NOT NULL,/*SE GUARDA EL SEGUNDO NOMBRE PARA MEJORAR EL RENDIMIENTO DE ALMACENAMIENTO*/
    primer_apellido_empleado VARCHAR(20) NOT NULL,/*SE GUARDA EL PRIMER APELLIDO PARA MEJORAR EL RENDIMIENTO DE ALMACENAMIENTO*/
    segundo_apellido_empleado VARCHAR(20) NOT NULL,/*SE GUARDA EL SEGUNDO APELLIDO PARA MEJORAR EL RENDIMIENTO DE ALMACENAMIENTO*/
    telefono_empleado VARCHAR(13) NOT NULL,/*SE SOLICITARA EL NUMERO DEL EMPLEADOS POR POSIBLES LLAMADAS DE ATENCION O INFORMACION*/
    direccion_empleado CHAR(30) NOT NULL/*LA ZONA DONDE VIVE NUESTRO EMPLEADO PARA LLAMARLO*/
);/*CERRAMOS NUESTRA TABLA DE EMPLEADOS CON SUS CONTENIDOS */

CREATE TABLE cliente(/*CREAREMOS UNA TABLA QUE SE LLAME CLIENTE VA A CONTENER LA INFORMACION DE LOS CLIENTES*/
    id_cliente INT NOT NULL PRIMARY KEY,/*SERA EL NUMERO DEL CLIENTE DONDE SE PODRA IDENTIFICARLO Y BUSCARLO MAS FACIL*/
    primer_nombre_cliente VARCHAR(20) NOT NULL,/*SE ALMACENARA EL PRIMER NOMBRE DEL CLIENTE */
    segundo_nombre_cliente VARCHAR(20) NOT NULL,/*SE ALMACENARA EL SEGUNDO NOMBRE DEL CLIENTE*/
    primer_apellido_cliente VARCHAR(20) NOT NULL,/*SE ALAMACENARA EL PRIMER APELLIDO DEL CLIENTE*/
    segundo_apellido_cliente VARCHAR(20) NOT NULL,/*SE ALMACENARA EL SEGUNDO APELLIDO DEL CLIENTE*/
    telefono_cliente VARCHAR(13) NOT NULL,/*EL NUMERO DEL CLIENTE PARA LLAMARLO Y SABER DE LOS SOPORTES REALIZADOS*/
    direccion_cliente VARCHAR(30) NOT NULL,
    fecha_cita VARCHAR(20)/*EL DIA QUE SE REALIZARA EL RESPECTIVO SOPORTE QUE A SOLICITADO*/
);/*CERRAMOS LA TABLA CLIENTES DONDE SE ALMACENARA EL CONTENIDO DEL CLIENTE*/

SHOW COLUMNS FROM negocio;/*SE MUESTRA EL CONTENIDO QUE SE TIENE EN ESTA TABLA DE NEGOCIO*/
SHOW COLUMNS FROM empleados;/*SE MOSTRARA LA TABLA CON SU CONTENIDO DE EMPLEADOS*/
SHOW COLUMNS FROM cliente;/*SE MOSTRARA LA TABLA DE CLIENTES DONDE LE PEDIMOS SU INFORMACION*/

INSERT INTO negocio (correo, direccion_negocio, horario_atencion, telefono) VALUES 
    ('techcare@gmail.com', 'Cra. 15 #78-33', '7 am - 6 pm', '3013445634'); --INSERTAMOS ESTOS VALORES A LA TABLA DE NEGOCIO

SELECT * FROM negocio;

INSERT INTO empleados (id_empleado, primer_nombre_empleado, segundo_nombre_empleado, primer_apellido_empleado, 
    segundo_apellido_empleado, telefono_empleado, direccion_empleado) VALUES
    (0001, 'Santiago', 'Enrique', 'Hernandez', 'Contreras', '5555555', 'direccion 1'),
    (0002, 'David', 'Nicolas', 'Chilito', 'Joaqui', '5545555', 'direccion 2'),
    (0003, 'Santiago', '', 'Baquero', 'Hurtado', '22244444', 'Desconocida'); --INSERTAMOS ESTOS VALORES A LA TABLA DE EMPLEADOS

SELECT * FROM empleados;

INSERT INTO cliente (id_cliente, primer_nombre_cliente, segundo_nombre_cliente, primer_apellido_cliente, 
    segundo_apellido_cliente, telefono_cliente, direccion_cliente, fecha_cita) VALUES
    (0001, 'Enrique', 'Leonardo', 'Martinez', 'Correa', '3013247112', 'direccion 1', '02/12/2022'),
    (0002, 'Cristo', 'David', 'Manchado', 'Fulano', '3016267412', 'direccion 2', '03/12/2022'),
    (0003, 'Abel', 'Fernando', 'Jurado', 'Zabaleta', '3003546114', 'direccion 3', '04/12/2022'), 
    (0004, 'William', 'Jose', 'Mendoza', 'Uribe', '45528902', 'direccion 4', '02/12/2022'); --INSERTAMOS ESTOS VALORES A LA TABLA DE EMPLEADOS

SELECT * FROM cliente;